:schedule:
  check_prices_worker:
    name: 'CheckPricesWorker - every 5min'
    cron: '*/1 * * * *'
    class: 'CheckPricesWorker'

    #cron: '30 8, * * *' # every day at 8:30am
    #cron: '30 8,12,18 * * *' # everyday at 8:30am, 12:30pm and 18:30pm
